### ISSUE TITLE
Change to const

### ISSUE THREAD

**Issue by lisannevvliet** [jornveltrop/progressive-web-apps-2122#10]
https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L12-L13

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L27-L28

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L32-L33

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L44

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L48-L49

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L66

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L68

https://github.com/jornveltrop/progressive-web-apps-2122/blob/af05d9709716139361e434af356fe900848290a5/app.js#L72-L73

**Comment by jornveltrop** [comment]
Thanks! Gefixt!
